/**
 * Generate the emoji catalog + vendor the color-emoji sprites.
 *
 * Sources (pinned devDependencies, see root package.json):
 *   - emojibase-data@17.0.0  (MIT)        — names, keywords, groups, skin-tone variants
 *   - @twemoji/svg@15.0.0    (graphics: CC-BY 4.0 © Twitter/jdecked; package: MIT)
 *
 * Outputs (COMMITTED, so builds never depend on this script):
 *   - packages/core/src/emoji-catalog.ts          compact catalog rows (generated)
 *   - apps/web/public/emoji/<hex>.svg             one sprite per catalog emoji + skin variant
 *   - apps/web/public/emoji/ATTRIBUTION.md        CC-BY 4.0 attribution (required)
 *
 * Run after bumping either package:
 *   npx tsx scripts/sync-emoji.ts            (EMOJI_NM=<dir containing the packages> to override)
 */
import { copyFileSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { emojiSpriteName } from "../packages/core/src/emoji-draw";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const NM = process.env.EMOJI_NM ? resolve(process.env.EMOJI_NM) : resolve(ROOT, "node_modules");
const OUT = resolve(ROOT, "apps/web/public/emoji");
const CAT = resolve(ROOT, "packages/core/src/emoji-catalog.ts");
const SVG_DIR = resolve(NM, "@twemoji/svg");

interface RawEmoji {
  label: string;
  emoji: string;
  tags?: string[];
  order?: number;
  group?: number;
  subgroup?: number;
  version: number;
  tone?: number | number[];
  skins?: RawEmoji[];
}
const DATA = JSON.parse(readFileSync(resolve(NM, "emojibase-data/en/data.json"), "utf8")) as RawEmoji[];
const MSG = JSON.parse(readFileSync(resolve(NM, "emojibase-data/en/messages.json"), "utf8")) as {
  groups: { key: string; message: string; order: number }[];
  subgroups: { key: string; message: string; order: number }[];
};

const have = new Set(readdirSync(SVG_DIR).filter((f) => f.endsWith(".svg")).map((f) => f.slice(0, -4)));
const keep = new Set<string>();
/** Resolve a sprite (rule from emojiSpriteName, tried with/without FE0F); null = no art. */
function sprite(e: string): string | null {
  for (const name of emojiSpriteName(e)) if (have.has(name)) return name;
  return null;
}

/** Drop a redundant VS16 from emoji that are already emoji-presentation (👍️ → 👍); keep it for ❤️-style text-default ones and ZWJ sequences. */
function norm(e: string): string {
  return !e.includes("\u200d") && /^\p{Emoji_Presentation}/u.test(e) ? e.replace(/\uFE0F/g, "") : e;
}

const groupIdx = new Map<number, number>();
const groups: { key: string; label: string }[] = [];
for (const g of MSG.groups.slice().sort((a, b) => a.order - b.order)) {
  if (g.key === "component") continue;
  groupIdx.set(g.order, groups.length);
  groups.push({ key: g.key, label: g.message.replace(/\b\w/g, (c) => c.toUpperCase()) });
}
const subgroups: string[] = [];
const subIdx = new Map<number, number>();
for (const s of MSG.subgroups.slice().sort((a, b) => a.order - b.order)) {
  subIdx.set(s.order, subgroups.length);
  subgroups.push(s.key);
}

const rows: unknown[] = [];
let skinVariants = 0;
let dropped = 0;
for (const e of DATA.slice().sort((a, b) => (a.order ?? 0) - (b.order ?? 0))) {
  if (e.group === undefined || !groupIdx.has(e.group)) continue;
  const s = sprite(e.emoji);
  if (!s) {
    dropped++;
    continue;
  }
  keep.add(s);
  let skins: string[] | undefined;
  if (e.skins?.length) {
    const byTone: (string | undefined)[] = [];
    for (const k of e.skins) {
      const kt = k.tone;
      const t = Array.isArray(kt) ? (kt.every((x) => x === kt[0]) ? kt[0] : undefined) : kt;
      if (t && t >= 1 && t <= 5 && sprite(k.emoji)) byTone[t - 1] = k.emoji;
    }
    if (byTone.length === 5 && byTone.every(Boolean)) {
      skins = (byTone as string[]).map(norm);
      for (const k of skins) {
        keep.add(sprite(k)!);
        skinVariants++;
      }
    }
  }
  const words = [...new Set([...(e.tags ?? []), ...e.label.toLowerCase().split(/[^a-z0-9]+/).filter(Boolean)])].join(" ");
  const row: unknown[] = [norm(e.emoji), e.label, words, groupIdx.get(e.group)!, subIdx.get(e.subgroup ?? 0) ?? 0];
  if (skins) row.push(skins);
  rows.push(row);
}

// Vendor sprites (wipe stale files first so removals propagate).
mkdirSync(OUT, { recursive: true });
for (const f of readdirSync(OUT)) if (f.endsWith(".svg")) rmSync(resolve(OUT, f));
for (const name of keep) copyFileSync(resolve(SVG_DIR, `${name}.svg`), resolve(OUT, `${name}.svg`));

const j = (v: unknown): string => JSON.stringify(v);
writeFileSync(
  CAT,
  `/**
 * GENERATED by scripts/sync-emoji.ts — do not edit by hand.
 * Source: emojibase-data@17.0.0 (MIT) filtered to emoji that have Twemoji 15.0 art.
 * ${rows.length} emoji (+ ${skinVariants} skin-tone variants).
 */
export const EMOJI_GROUPS: readonly { key: string; label: string }[] = ${j(groups)};
export const EMOJI_SUBGROUPS: readonly string[] = ${j(subgroups)};
/** [emoji, name, space-separated keywords, group index, subgroup index, skin-tone variants (tones 1..5)?] */
export type EmojiRow = readonly [string, string, string, number, number, (readonly string[])?];
export const EMOJI_ROWS: readonly EmojiRow[] = [
${rows.map((r) => "  " + j(r)).join(",\n")},
];
`,
);
writeFileSync(
  resolve(OUT, "ATTRIBUTION.md"),
  `# Emoji artwork attribution

The color emoji sprites in this folder are **Twemoji** graphics
(https://github.com/jdecked/twemoji), Copyright 2020 Twitter, Inc and other contributors,
licensed under **CC-BY 4.0** (https://creativecommons.org/licenses/by/4.0/).
Vendored from the npm package \`@twemoji/svg@15.0.0\` (optimized SVGs, MIT-licensed packaging).
No changes were made to the artwork other than the file optimization done upstream.

Emoji names, keywords and grouping come from \`emojibase-data@17.0.0\` (MIT), derived from
Unicode CLDR / emoji data (Unicode License v3).
`,
);
console.log(`emoji: ${rows.length} base rows, ${skinVariants} skin variants, ${keep.size} sprites, ${dropped} dropped (no art)`);
