/**
 * Vendor the bundled font library (FONT_LIBRARY in @cadence/core) from the pinned
 * @fontsource devDependencies into the web app, so BOTH renderers use the same
 * files:
 *   - apps/web/public/fonts/<id>/<id>-<subset>-<weight>-<style>.woff2  (served to
 *     the browser; also registered with Skia by @cadence/render-node for export)
 *   - apps/web/src/app/fonts.css  (@font-face rules with the upstream unicode-range)
 *   - apps/web/public/fonts/LICENSES.md  (per-family license, from each package)
 *
 * Run after changing FONT_LIBRARY or bumping a @fontsource version:
 *   npx tsx scripts/sync-fonts.ts
 * The outputs are committed, so builds never depend on this script.
 */
import { copyFileSync, mkdirSync, readFileSync, rmSync, writeFileSync, existsSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { FONT_LIBRARY, FONT_SUBSETS, fontFilePath, fontFiles } from "@cadence/core";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = resolve(ROOT, "apps/web/public/fonts");
const CSS_OUT = resolve(ROOT, "apps/web/src/app/fonts.css");

/** unicode-range of the @font-face block that loads `file` in a fontsource CSS file. */
function unicodeRange(css: string, file: string): string | null {
  for (const block of css.split("@font-face").slice(1)) {
    if (!block.includes(`/files/${file}`)) continue;
    return block.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim() ?? null;
  }
  return null;
}

rmSync(OUT, { recursive: true, force: true });
mkdirSync(OUT, { recursive: true });
const css: string[] = [
  "/* GENERATED by scripts/sync-fonts.ts — do not edit. Bundled OFL/Apache Google Fonts. */",
];
const licenses: string[] = ["# Bundled font licenses", "", "Vendored from @fontsource by scripts/sync-fonts.ts.", ""];
let files = 0;

for (const face of FONT_LIBRARY) {
  const pkg = resolve(ROOT, "node_modules/@fontsource", face.id);
  const meta = JSON.parse(readFileSync(resolve(pkg, "package.json"), "utf8")) as { version: string; license: string };
  licenses.push(`- **${face.family}** — ${meta.license} (@fontsource/${face.id}@${meta.version})`);
  mkdirSync(resolve(OUT, face.id), { recursive: true });
  for (const { weight, style } of fontFiles(face)) {
    const cssFile = resolve(pkg, style === "italic" ? `${weight}-italic.css` : `${weight}.css`);
    const upstream = existsSync(cssFile) ? readFileSync(cssFile, "utf8") : "";
    for (const subset of FONT_SUBSETS) {
      const rel = fontFilePath(face, subset, weight, style);
      const src = resolve(pkg, "files", rel.split("/")[1]!);
      if (!existsSync(src)) continue; // some faces ship no latin-ext
      copyFileSync(src, resolve(OUT, rel));
      files++;
      const range = unicodeRange(upstream, rel.split("/")[1]!);
      css.push(
        `@font-face{font-family:'${face.family}';font-style:${style};font-weight:${weight};font-display:swap;` +
          `src:url(/fonts/${rel}) format('woff2');${range ? `unicode-range:${range};` : ""}}`,
      );
    }
  }
}

writeFileSync(CSS_OUT, css.join("\n") + "\n");
writeFileSync(resolve(OUT, "LICENSES.md"), licenses.join("\n") + "\n");
console.log(`synced ${FONT_LIBRARY.length} families, ${files} files → ${OUT}`);
